---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: konnectivity-agent
  namespace: kube-system
  labels:
    app: konnectivity-agent
spec:
  selector:
    matchLabels:
      app: konnectivity-agent
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 10%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: konnectivity-agent
    spec:
      automountServiceAccountToken: false
      priorityClassName: system-node-critical
      containers:
      - name: konnectivity-agent
        image: {{ imageFor "apiserver-network-proxy" }}
        imagePullPolicy: IfNotPresent
{{- if .KonnectivitySecurityContext }}
{{- $securityContext := .KonnectivitySecurityContext }}
        securityContext:
          runAsUser: {{ $securityContext.RunAsUser }}
{{- end }}
        command: ["/bin/proxy-agent"]
        args: [
          "--logtostderr=true",
          "--ca-cert=/etc/konnectivity/ca/ca.crt",
          "--proxy-server-host={{ .KonnectivityServerURL }}",
          "--proxy-server-port={{ .KonnectivityServerNodePort }}",
          "--health-server-port={{ .KonnectivityAgentHealthPort }}",
          "--agent-cert=/etc/konnectivity/agent/tls.crt",
          "--agent-key=/etc/konnectivity/agent/tls.key",
          "--agent-identifiers=default-route=true",
          "--keepalive-time=30s",
          "--probe-interval=5s",
          "--sync-interval=5s",
          "--sync-interval-cap=30s",
          "--v=3"
          ]
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .KonnectivityAgentHealthPort }}
            scheme: HTTP
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 6
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: {{ .KonnectivityAgentHealthPort }}
            scheme: HTTP
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 1
          timeoutSeconds: 5
        startupProbe:
          httpGet:
            path: /healthz
            port: {{ .KonnectivityAgentHealthPort }}
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 60
          timeoutSeconds: 5
{{- if .KonnectivityAgentDataPlaneContainerResources }}
        resources: {{ range .KonnectivityAgentDataPlaneContainerResources }}{{ range .ResourceRequest }}
          requests: {{ if .CPU }}
            cpu: {{ .CPU }}{{ end }}{{ if .Memory }}
            memory: {{ .Memory }}{{ end }}{{ end }}{{ end }}
{{- end }}
        volumeMounts:
        - mountPath: /etc/konnectivity/ca
          name: konnectivity-ca
        - mountPath: /etc/konnectivity/agent
          name: agent-certs
      dnsPolicy: Default
      tolerations:
      - operator: "Exists"
      volumes:
      - name: agent-certs
        secret:
          secretName: konnectivity-agent
          defaultMode: 0640
      - name: konnectivity-ca
        configMap:
          defaultMode: 0640
          name: konnectivity-ca-bundle
