apiVersion: config.openshift.io/v1
kind: FeatureGate
metadata:
  name: cluster
spec:
  featureSet: CustomNoUpgrade
  customNoUpgrade:
    enabled:
    - RotateKubeletServerCertificate
    disabled:
    - RetroactiveDefaultStorageClass
