apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: "/etc/kubernetes/secret/kubeconfig"
leaderElection:
  leaderElect: true
  leaseDuration: 60s
  renewDeadline: 15s
  retryPeriod: 3s
