kind: Deployment
apiVersion: apps/v1
metadata:
  name: kube-scheduler
spec:
  replicas: {{ .Replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
  selector:
    matchLabels:
      app: kube-scheduler
  template:
    metadata:
      labels:
        app: kube-scheduler
        clusterID: "{{ .ClusterID }}"
{{ if .RestartDate }}
      annotations:
        openshift.io/restartedAt: "{{ .RestartDate }}"
{{ end }}
    spec:
      tolerations:
        - key: "multi-az-worker"
          operator: "Equal"
          value: "true"
          effect: NoSchedule
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: clusterID
                      operator: In
                      values: ["{{ .ClusterID }}"]
                topologyKey: "kubernetes.io/hostname"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values: ["kube-scheduler"]
              topologyKey: "kubernetes.io/hostname"
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values: ["kube-scheduler"]
              topologyKey: "failure-domain.beta.kubernetes.io/zone"
      automountServiceAccountToken: false
{{ if .MasterPriorityClass }}
      priorityClassName: {{ .MasterPriorityClass }}
{{ end }}
      containers:
      - name: kube-scheduler
{{- if .KubeSchedulerSecurityContext }}
{{- $securityContext := .KubeSchedulerSecurityContext }}
        securityContext:
          runAsUser: {{ $securityContext.RunAsUser }}
{{- end }}
        image: {{ imageFor "hyperkube" }}
        command:
        - hyperkube
        - kube-scheduler
        args:
        - "--config=/etc/kubernetes/config/config.yaml"
        - "--cert-dir=/var/run/kubernetes"
        - "--port=0"
        - "--authentication-kubeconfig=/etc/kubernetes/secret/kubeconfig"
        - "--authorization-kubeconfig=/etc/kubernetes/secret/kubeconfig"
        - "--tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,TLS_AES_128_GCM_SHA256,TLS_CHACHA20_POLY1305_SHA256,TLS_AES_256_GCM_SHA384"
        - "-v=2"
        {{ range $featureGate := .DefaultFeatureGates }}- "--feature-gates={{ $featureGate }}"
        {{ end }}{{ range $featureGate := .ExtraFeatureGates }}- "--feature-gates={{ $featureGate }}"
        {{ end }}
{{ if .KubeSchedulerResources }}
        resources:{{ range .KubeSchedulerResources }}{{ range .ResourceRequest }}
          requests: {{ if .CPU }}
            cpu: {{ .CPU }}{{ end }}{{ if .Memory }}
            memory: {{ .Memory }}{{ end }}{{ end }}{{ range .ResourceLimit }}
          limits: {{ if .CPU }}
            cpu: {{ .CPU }}{{ end }}{{ if .Memory }}
            memory: {{ .Memory }}{{ end }}{{ end }}{{ end }}
{{ end }}
{{- if .SchedulerLivenessProbe }}
{{- $probe := .SchedulerLivenessProbe }}
        livenessProbe:
          httpGet:
            scheme: {{ or $probe.HttpGet.Scheme "HTTPS" }}
            port: {{ or $probe.HttpGet.Port 10259 }}
            path: {{ or $probe.HttpGet.Path "healthz" }}
          initialDelaySeconds: {{ or $probe.InitialDelaySeconds 10 }}
          periodSeconds: {{ or $probe.PeriodSeconds 10 }}
          timeoutSeconds: {{ or $probe.TimeoutSeconds 1 }}
          failureThreshold: {{ or $probe.FailureThreshold 3 }}
          successThreshold: {{ or $probe.SuccessThreshold 1 }}
{{- end }}
        volumeMounts:
        - mountPath: /etc/kubernetes/secret
          name: secret
        - mountPath: /etc/kubernetes/config
          name: config
        - mountPath: /var/run/kubernetes/
          name: cert
        workDir: /var/run/kubernetes
      volumes:
      - secret:
          secretName: service-network-admin-kubeconfig
        name: secret
      - configMap:
          name: kube-scheduler-config
        name: config
      - emptyDir: {}
        name: cert
