kind: Deployment
apiVersion: apps/v1
metadata:
  name: cluster-policy-controller
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: cluster-policy-controller
  minReadySeconds: 30
  template:
    metadata:
      labels:
        app: cluster-policy-controller
        clusterID: "{{ .ClusterID }}"
{{ if .RestartDate }}
      annotations:
        openshift.io/restartedAt: "{{ .RestartDate }}"
{{ end }}
    spec:
      tolerations:
        - key: "multi-az-worker"
          operator: "Equal"
          value: "true"
          effect: NoSchedule
        - key: "dedicated"
          operator: "Equal"
          value: "master-{{ .ClusterID }}"
          effect: NoSchedule
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: dedicated
                operator: In
                values:
                - master-{{ .ClusterID }}
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: clusterID
                      operator: In
                      values: ["{{ .ClusterID }}"]
                topologyKey: "kubernetes.io/hostname"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values: ["cluster-policy-controller"]
              topologyKey: "kubernetes.io/hostname"
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values: ["cluster-policy-controller"]
              topologyKey: "topology.kubernetes.io/zone"
      automountServiceAccountToken: false
{{ if .MasterPriorityClass }}
      priorityClassName: {{ .MasterPriorityClass }}
{{ end }}
      containers:
      - name: cluster-policy-controller
{{- if .ClusterPolicyControllerSecurityContext }}
{{- $securityContext := .ClusterPolicyControllerSecurityContext }}
        securityContext:
          runAsUser: {{ $securityContext.RunAsUser }}
{{- end }}
        image: {{ imageFor "cluster-policy-controller" }}
        command:
        - "cluster-policy-controller"
        args:
        - "start"
        - "--config=/etc/kubernetes/cmconfig/config.yaml"
        - "--kubeconfig=/etc/kubernetes/secret/kubeconfig"
        - "--namespace=openshift-kube-controller-manager"
        env:
        - name: POD_NAMESPACE
          value: openshift-kube-controller-manager
{{ if .ClusterPolicyControllerResources }}
        resources:{{ range .ClusterPolicyControllerResources }}{{ range .ResourceRequest }}
          requests: {{ if .CPU }}
            cpu: {{ .CPU }}{{ end }}{{ if .Memory }}
            memory: {{ .Memory }}{{ end }}{{ end }}{{ range .ResourceLimit }}
          limits: {{ if .CPU }}
            cpu: {{ .CPU }}{{ end }}{{ if .Memory }}
            memory: {{ .Memory }}{{ end }}{{ end }}{{ end }}
{{ end }}
        volumeMounts:
        - mountPath: /etc/kubernetes/secret
          name: secret
        - mountPath: /etc/kubernetes/cmconfig
          name: cmconfig
        - mountPath: /etc/kubernetes/config
          name: config
      volumes:
      - secret:
          secretName: openshift-controller-manager
          defaultMode: 0640
        name: secret
      - configMap:
          name: openshift-controller-manager
        name: config
      - configMap:
          name: openshift-controller-manager-config
        name: cmconfig
